### ISSUE TITLE
To-do List(2020/04/27)

### ISSUE THREAD

**Issue by ttubuckee** [ARmera/graduation-project#4]
화이팅 ㅎㅎ

**Comment by ttubuckee** [comment]
20200427
- [ ] object detection/ tracking 관련 정보 검색 & 학습
- [ ] 개발환경 설정
- [ ] 각 기능 사용 기술 명세

**Comment by KimSeongHeon** [comment]
@ttubuckee  안녕

**Comment by ttubuckee** [comment]
@KimSeongHeon  안녕2

**Comment by ttubuckee** [comment]
20200504
- [ ] 클래스 다이어그램 작성
- [ ] 설계서 작성 (due 5/11)

**Comment by ttubuckee** [comment]
20200511

**Comment by KimSeongHeon** [comment]
- [ ] 클래스 다이어그램 상세 설명 작성(각자 분할하여 집에서 작성할 것)
- [ ] 시스템 설계도(시퀀스 다이어그램 사용)
- [ ] 각 메소드 동작 흐름 다이어그램 그리기

전체적으로 틀만 잡고 각자 작성 하는게 좋아보임

**Comment by ttubuckee** [comment]
20200518

## [ ] 일일 활동 보고서 작성
## [ ] 시퀀스 다이어그램 추가 작성

**Comment by ttubuckee** [comment]
20200518

- [ ] 일일 활동 보고서 작성
- [ ] 시퀀스 다이어그램 추가 작성

**Comment by ttubuckee** [comment]
20200525

- [ ] 일일 활동 보고서 작성
- [ ] 설계서 발표준비

**Comment by ttubuckee** [comment]
20200603

- [ ] 피드백을 바탕으로 시퀀스 다이어그램 수정
- [ ] 간단한 클론 코딩
