### ISSUE TITLE
To-do List(2020/5/11)

### ISSUE THREAD

**Issue by KimSeongHeon** [ARmera/graduation-project#5]
- [x] 클래스 다이어그램 상세 설명 작성(각자 분할하여 집에서 작성할 것)
- [x] 시스템 설계도(시퀀스 다이어그램 사용)
- [ ] 각 메소드 동작 흐름 다이어그램 그리기

전체적으로 틀만 잡고 각자 작성 하는게 좋아보임
